### ISSUE TITLE
Runtime errors in a  distillery release

### ISSUE THREAD

**Issue by stephenmoloney** [sikanhe/apollo-tracing-elixir#14]
***Problem:***
absinthe_plug is a project dependency and the following error occurs during runtime making a request in a distillery release.

***Description:***
```
Request: POST /api
** (exit) an exception was raised:
    ** (RuntimeError)   You don't have Plug loaded, please use
  ApolloTracing.Pipeline.default(absinthe_schema, pipeline_opts)
  to produce a pipeline without Plug specific phases

        (apollo_tracing) lib/apollo_tracing/pipeline.ex:16: ApolloTracing.Pipeline.plug/2
        (absinthe_plug) lib/absinthe/plug/request/query.ex:75: Absinthe.Plug.Request.Query.add_pipeline/3
```

It seems to be because Distillery doesn't find the Absinthe.Plug module... 
```
  if Code.ensure_loaded?(Absinthe.Plug) do
    def plug(config, pipeline_opts \\ []) do
      config
      |> Absinthe.Plug.default_pipeline(pipeline_opts)
      |> add_phases()
    end
  else
    def plug(_, _ \\ []) do
      raise RuntimeError, """
        You don't have Plug loaded, please use
        ApolloTracing.Pipeline.default(absinthe_schema, pipeline_opts)
        to produce a pipeline without Plug specific phases
      """
    end
  end
```

***One Possible Solution:***
Relates to [PR](https://github.com/sikanhe/apollo-tracing-elixir/pull/13)

**Comment by sikanhe** [comment]
Does adding absinthe_plug to your project solve the problem? I don't see why we need to include absinthe_plug in this library.

**Comment by weaktyper** [comment]
There is probably other ways to do so within my umbrella app project and without adding this dependency in `apollo-tracing-elixir`... maybe something along the lines of ensuring the applications are started in the correct order, maybe `Application.ensure_started` but I'm not certain how to approach it that way. But if there is such a way, I think it should be documented somewhere.

In the end, I opted for just adding the dependency into this project directly by adding `{:absinthe_plug, "~> 1.4"}` to the `deps/0` in `mix.exs`.

**Comment by stephenmoloney** [comment]
There is probably other ways to do so within my umbrella app project and without adding this dependency in `apollo-tracing-elixir`... maybe something along the lines of ensuring the applications are started in the correct order, maybe `Application.ensure_started` but I'm not certain how to approach it that way. But if there is such a way, I think it should be documented somewhere.

In the end, I opted for just adding the dependency into this project directly by adding `{:absinthe_plug, "~> 1.4"}` to the `deps/0` in `mix.exs` and yes, that solved the problem which was the runtime error above.

perhaps, `{:absinthe_plug, "~> 1.4", optional: true}` would work too.
