### ISSUE TITLE
This trace information is incomplete ?

### ISSUE THREAD

**Issue by mydearxym** [sikanhe/apollo-tracing-elixir#19]
![image](https://user-images.githubusercontent.com/6184465/37745713-4562e720-2db1-11e8-8ecd-f9e2f3603b85.png)

![image](https://user-images.githubusercontent.com/6184465/37745715-525818d8-2db1-11e8-8aa2-2fa3a078d49e.png)

![image](https://user-images.githubusercontent.com/6184465/37745748-963b54e8-2db1-11e8-8058-6eb82781c968.png)

currently the only tracing info is request / response time, seems field level tracing is missing ?

**Comment by athal7** [comment]
I'm not seeing this same error with our integration. Can you please post the version you are using, and how you are registering tracing in your application.

**Comment by mydearxym** [comment]
thanks @athal7 

elixir version:   Elixir 1.6.4 (compiled with OTP 20)
macOS: 10.13.1

related deps  [source code](https://github.com/mydearxym/mastani_server/blob/dev/mix.exs): 


```elixir
defp deps do
    [
      {:phoenix, "~> 1.3.2"},
      {:phoenix_pubsub, "~> 1.0.2"},
      {:phoenix_ecto, "~> 3.3.0"},
      {:ecto, "~> 2.2.9"},
      {:absinthe, "~> 1.4.8"},
      {:absinthe_ecto, "~> 0.1.3"},
      {:absinthe_plug, "~> 1.4.2"},
      {:dataloader, "~> 1.0.0"},
      {:apollo_tracing, "~> 0.4.1"},
     .....
    ]
  end

```

schema.ex [source](https://github.com/mydearxym/mastani_server/blob/dev/lib/mastani_server_web/schema.ex#L36) : 

``` elixir 
  def middleware(middleware, _field, %{identifier: :query}) do
    middleware ++ [Middleware.GeneralError]
  end

  def middleware(middleware, _field, %{identifier: :mutation}) do
    middleware ++ [Middleware.ChangesetErrors]
  end

  def middleware(middleware, _field, _object) do
    middleware ++ [ApolloTracing.Middleware.Tracing, ApolloTracing.Middleware.Caching]
    # middleware
  end
```

**Comment by mydearxym** [comment]
my mistake: 
i should put tracing middleware at the beginning : 

```elixir
def middleware(middleware, _field, _object) do
   [ApolloTracing.Middleware.Tracing, ApolloTracing.Middleware.Caching] ++ middleware
   # middleware
end
```

**Comment by athal7** [comment]
I think it actually had to do with a previous recommendation we had in the readme calling out the different identifiers (which it looks like you had). The new configuration you have is correct. Sorry for the trouble!
