### ISSUE TITLE
What's the status of this project?

### ISSUE THREAD

**Issue by ghost** [sikanhe/apollo-tracing-elixir#21]
Hi there, just checking. Is this being maintained? What features are missing? Do you need help?

**Comment by athal7** [comment]
Hi @rparcus! I've been using this project in production for about a year now and have been contributing with @sikanhe. 

There are a couple of open issues that you might consider looking into if you're interested. Additionally it could be beneficial to ensure compatibility with the latest Elixir and Phoenix releases.

The biggest feature I think we'd want to tackle longer term is subscription tracing, but Apollo doesn't support that yet, so it's not something we are able to address yet.

**Comment by fbjork** [comment]
@athal7 @sikanhe any plans on supporting the new Apollo Service 2 protocol?

**Comment by athal7** [comment]
@fbjork I’m not familiar with that, can you send documentation?

My understanding of Apollo Server 2 is that it is a node-specific backend, and that their engine proxy (what is to be used with this tool) will only continue to support a subset of engine features, but not new ones.

https://www.apollographql.com/docs/references/engine-proxy.html

Please re-open a specific issue to this topic if I’ve misrepresented.

**Comment by fbjork** [comment]
@athal7 ok, created this issue instead: https://github.com/sikanhe/apollo-tracing-elixir/issues/22
