### ISSUE TITLE
Send metrics directly to Apollo Platform

### ISSUE THREAD

**Issue by fbjork** [sikanhe/apollo-tracing-elixir#22]
Now that Engine is officially deprecated, it would be great to see support for sending metrics directly to the Apollo Platform from this library.

There's no official documentation yet, but this is a good start:
https://github.com/apollographql/apollo/pull/263/files

**Comment by athal7** [comment]
The status of engine is a bit unclear:

> That said, the proxy is still a good option for getting set up with Engine in a few specific circumstances:
> 
> 1. You are not using Apollo Server, your server has an apollo-tracing plugin, and you want to get performance metrics insights.
> 2. You are relying on full query caching in your infrastructure.
> 3. You are not using Apollo Server and you want to use Apollo’s automatic persisted queries.

This use case falls directly in # 1, so personally I don't plan to make big sweeping changes to push directly to engine anytime soon, but feel free to work on it if you think it's important.

**Comment by maartenvanvliet** [comment]
I've been working on a hex package to do the reporting to Apollo Engine. It builds upon `apollo-tracing-elixir` to collect the tracing information. The tracing information is collected, converted to protocol buffers and send to Engine. See https://github.com/maartenvanvliet/absinthe_trace_reporter

It is far from done and I could use some help in finishing it. Main blocker is converting the list of traces (list of %ApolloTracing.Schema{}) to the tree that Engine expects. The current test cases should be good but running it against some real graphql schemas revealed some bugs in the conversion. 
Other issues are mostly configuration and cleanup.

**Comment by athal7** [comment]
That's awesome @maartenvanvliet. Thanks for sharing!
