### ISSUE TITLE
cache info not fetched by apollo engine?

### ISSUE THREAD

**Issue by mydearxym** [sikanhe/apollo-tracing-elixir#23]
hello there :)

i setup apollo ltracing then add meta to my schema:

![image](https://user-images.githubusercontent.com/6184465/50759357-c5d9dc00-129f-11e9-99e0-345cdcc50f48.png)

but the cache hint is always empty:

![image](https://user-images.githubusercontent.com/6184465/50759781-f3735500-12a0-11e9-8dbf-11a7797677e0.png)

also the apollo-engine seems not receive the cache info

![image](https://user-images.githubusercontent.com/6184465/50759474-0fc2c200-12a0-11e9-86f8-368c95750d18.png)

![image](https://user-images.githubusercontent.com/6184465/50759487-18b39380-12a0-11e9-9341-99c627b53577.png)

Why isn't this caching anything?

**Comment by athal7** [comment]
I just tried to reproduce this in the tests, and also updated the reps to use the version of absinthe and absinthe_plug that are in your referenced implementation repository, however, I'm not able to achieve a test failure. Can you verify that the middleware is being called in your integration? The multiple-definition of the middleware function in your `schema.ex` seems like it might possibly prevent this code from being called.

**Comment by mydearxym** [comment]
@athal7 thanks for the help
>The multiple-definition of the middleware function in your schema.ex seems like it might possibly prevent this code from being called.

as you said, this it's the main reason, i changed the middleware order ant it works 🎉 !
![image](https://user-images.githubusercontent.com/6184465/51068119-94249480-1654-11e9-9a62-558b5e32cdd5.png)
![image](https://user-images.githubusercontent.com/6184465/51068126-aa325500-1654-11e9-9562-04518ce34d04.png)


but still a little issue: 

this meta style works: 
![image](https://user-images.githubusercontent.com/6184465/51068140-d5b53f80-1654-11e9-9bed-cccd4894f208.png)

this not work: 
![image](https://user-images.githubusercontent.com/6184465/51068146-ebc30000-1654-11e9-8643-b8c0a5158679.png)

**Comment by athal7** [comment]
That’s great to hear!

It doesn’t look like you have the cache keyword in your second implementation. 

I think the readme needs to be updated, since there is not a test case for the implementation suggested there.
